Make it possible to implement your own network layer #58
parley-messaging/android-library pull request #68
Opened 2024-09-10 15:00 UTC by mennovogel

This fixes #58

I've made it optional to use Retrofit and its configurations (OkHttp and Gson). 

Just like it was already possible to implement your own version of the ParleyLaunchCallback with a default implementation of DefaultParleyLaunchCallback, I've used the same logic to implement your own version of the newly added NetworkConfig interface. A DefaultNetworkConfig is included and is used by default, so no changes are needed on a version update of Parley.

Let me know if you have questions or other comments.

2024-09-10 15:03 UTC, mennovogel commented on parley/src/main/java/nu/parley/android/data/net/service/DeviceService.kt
I've converted the Retrofit Services interfaces to Kotlin.

2024-09-11 08:54 UTC, alexkok requested changes

2024-09-11 08:54 UTC, alexkok commented on parley/src/main/java/nu/parley/android/ParleyNetwork.java
> -    public Interceptor interceptor;
Agreed, good idea 👍

2024-09-11 09:03 UTC, alexkok commented
With this implementation, the developer would need to implement all repositories by their interfaces. 
Feels like a bit too much of a requirement to do so. It would be more neat if we just interface the Network Client instead. 

Doing so would maybe result in a change in how we use Retrofit, but that's alright. Interfacing only the network client would allow intercepting requests by the developer. And doesn't require them to implement all the repositories we have.

For example, in iOS we have:
```
class CustomNetworkSession : ParleyNetworkSession {
    func request(_ url: URL, data: Data?, method: ParleyHTTPRequestMethod, headers: [String : String], completion: @escaping (Result<ParleyHTTPDataResponse, ParleyHTTPErrorResponse>) -> Void) {
        // ...
    }
    
    func upload(data: Data, to url: URL, method: ParleyHTTPRequestMethod, headers: [String : String], completion: @escaping (Result<ParleyHTTPDataResponse, ParleyHTTPErrorResponse>) -> Void) {
        // ...
    }
}
```

After interfacing network client, we would like to align terminology with iOS (NetworkSession etc.) -- Or if we have ideas for better naming, we might as well adjust iOS to match these again in a backwards compatible way. We'll look at naming later.

What do you think about this? Would interfacing the network client work as well instead of interfacing the repositories?

_Sidenote: Also, Parley keeps the dependency on retrofit like this. But the good thing is that it's not a breaking change because of that, so that's great, that's good for now. We'll likely separate that when a v4 comes (note that v4 is not planned yet)._

2024-09-11 09:06 UTC, alexkok commented on parley/src/main/java/nu/parley/android/util/DeviceUtil.java
Perfect, yeah that is nice anyway, to separate that logic

2024-09-11 10:57 UTC, mennovogel commented
> With this implementation, the developer would need to implement all repositories by their interfaces.
> Feels like a bit too much of a requirement to do so. It would be more neat if we just interface the Network Client instead.
> 
> Doing so would maybe result in a change in how we use Retrofit, but that's alright. Interfacing only the network client would allow intercepting requests by the developer. And doesn't require them to implement all the repositories we have.
> 

I've looked at the iOS implementation, but I didn't think it was possible without a lot of refactoring and/or removing the usage of Retrofit. Now that I think more about it, we might be able to alter the usage of it and use Retrofit only for passing Strings, without the json mapping. I'll look into that.

> After interfacing network client, we would like to align terminology with iOS (NetworkSession etc.) 

I'll check the naming and adjust it.

2024-09-13 15:20 UTC, mennovogel commented
As I proposed, I've changed the way we use Retrofit, now it only passes Strings and the json parsing is always done by the Parley library. This makes it easier to implement the ParleyNetworkSession interface.

2024-09-18 09:09 UTC, mennovogel commented
@alexkok
Could you have another look please?

2024-09-18 12:36 UTC, alexkok commented
Thanks @mennovogel ! Looks very good 👍 

FYI: Found another issue, but that is not related to these changes. So fixing that as well now before creating a new version.

2024-09-18 12:36 UTC, alexkok approved these changes

2024-09-18 12:36 UTC, merged

2024-09-18 13:56 UTC, alexkok commented
Released in [3.11.0](https://github.com/parley-messaging/android-library/releases/tag/3.11.0) 🚀