Add: Parley.setUniqueDeviceIdentifier()
parley-messaging/android-library pull request #7
Opened 2022-03-09 14:53 UTC by Rolf-Smit

Currently Parley uses the `Settings.Secure.ANDROID_ID` as unique device identifier, but that comes with a few problems:

- This identifier is not recommended to be used by Google
- This identifier can behave differently on different Android versions
- On more recent Android versions this identifier only resets if the whole device is reset, not on app reinstall.
- Without the ability to change the device ID that Parley uses, it is not possible to fully separate 2 chat users without resetting the device. For example: in an app I'm working on a user can login but also logout, allowing another user to use the app. Both users will now use the same device ID, which is less then ideal.

This pull-request adds a method to manually override the device ID that Parley uses (`Parley.setUniqueDeviceIdentifier()`), it also adds a warning (Logcat) if no manual ID is provided.

2022-03-10 12:56 UTC, Rolf-Smit commented
Update:

Instead of a setter method, the unique device identifier can now be provided through the `configure()` methods.

2022-03-10 15:35 UTC, alexkok commented
Thanks @Rolf-Smit ! Looks good -- Requested a few changes.

As for the deprecated note: We will remain the default `ANDROID_ID` usage in the upcoming update for backwards compatible reasons, but will likely update this in a later version by removing the `ANDROID_ID` usage fully. However, for the upcoming update the warning will clearly indicate it at least 👍

2022-03-11 10:42 UTC, alexkok requested changes

2022-03-11 11:17 UTC, Rolf-Smit commented on parley/src/main/java/nu/parley/android/Parley.java
> +    @Deprecated
Done.

2022-03-11 11:17 UTC, Rolf-Smit commented on parley/src/main/java/nu/parley/android/Parley.java
> +    @Deprecated
Done.

2022-03-11 11:17 UTC, Rolf-Smit commented on parley/src/main/java/nu/parley/android/Parley.java
> +     * It is highly recommended to use this method over the deprecated
Done.

2022-03-11 11:18 UTC, Rolf-Smit commented
I've implemented the requested changes :)

2022-03-11 12:41 UTC, alexkok approved these changes

2022-03-11 12:47 UTC, alexkok commented
Thanks 👍

2022-03-11 12:47 UTC, merged